-- SCRIPT ROLLBACK DELTA_001
DROP TABLE FUNCIONARIO_TELEFONE
DROP TABLE FUNCIONARIO;
DROP TABLE USUARIO_TELEFONE
DROP TABLE USUARIO;
DROP TABLE TIPO_USUARIO;
DROP TABLE TELEFONE;
DROP TABLE TIPO_TELEFONE
DROP TABLE CIDADE
DROP TABLE ESTADO


-- SEQUENCES
DROP SEQUENCE SQ_TIPO_TELEFONE;
DROP SEQUENCE SQ_TELEFONE;
DROP SEQUENCE SQ_FUNCIONARIO;
