-- SCRIPT ROLLBACK DELTA_001
DROP TABLE PRODUTO_PEDIDO;
DROP TABLE PEDIDO;
DROP TABLE STATUS_PEDIDO;


-- SEQUENCES
DROP SEQUENCE SQ_STATUS_PEDIDO;
DROP SEQUENCE SQ_PEDIDO;
DROP SEQUENCE SQ_PRODUTO_PEDIDO;

