-- SCRIPT ROLLBACK DELTA_000
DROP TABLE PRODUTO
DROP TABLE TIPO_PRODUCAO
DROP TABLE TIPO_UNIDADE
DROP TABLE TIPO_VENDA;


-- SEQUENCES
DROP SEQUENCE SQ_TIPO_PRODUCAO;
DROP SEQUENCE SQ_TIPO_VENDA;
DROP SEQUENCE SQ_TIPO_UNIDADE;
DROP SEQUENCE SQ_PRODUTO;