ALTER TABLE tb_phone ALTER COLUMN IDCUSTOMER DROP NOT NULL;
ALTER TABLE tb_phone ALTER COLUMN IDEMPLOYEE DROP NOT NULL;
ALTER TABLE tb_phone ALTER COLUMN IDPROVIDER DROP NOT NULL;
ALTER TABLE tb_phone ALTER COLUMN IDUSER DROP NOT NULL;