-- DDL - sequences 001
CREATE SEQUENCE SQ_PRODUCT START 1;
CREATE SEQUENCE SQ_PRODUCT_OPERATION START 1;
CREATE SEQUENCE SQ_PRODUCTION_TYPE START 1;
CREATE SEQUENCE SQ_SALE_TYPE START 1;
CREATE SEQUENCE SQ_STOCK_TYPE START 1;
