-- DDL - sequences 002 - Customer - Employee - Provider  
CREATE SEQUENCE SQ_CUSTOMER START 1;
CREATE SEQUENCE SQ_CUSTOMER_OPERATION START 1;
CREATE SEQUENCE SQ_CUSTOMER_HISTORY START 1;


CREATE SEQUENCE SQ_PROVIDER START 1;
CREATE SEQUENCE SQ_PROVIDER_OPERATION START 1;
CREATE SEQUENCE SQ_PROVIDER_HISTORY START 1;


CREATE SEQUENCE SQ_EMPLOYEE START 1;
CREATE SEQUENCE SQ_EMPLOYEE_OPERATION START 1;
CREATE SEQUENCE SQ_EMPLOYEE_HISTORY START 1;

