-- DDL - sequences 002
CREATE SEQUENCE SQ_PRODUCT_HISTORY START 1;

CREATE SEQUENCE SQ_EXPENSE START 1;
CREATE SEQUENCE SQ_EXPENSE_ITEM START 1;
CREATE SEQUENCE SQ_EXPENSE_TYPE START 1;
CREATE SEQUENCE SQ_EXPENSE_STATUS START 1;
CREATE SEQUENCE SQ_EXPENSE_HISTORY START 1;
CREATE SEQUENCE SQ_EXPENSE_OPERATION START 1;