

-- INSERTS INICIAIS 002

-- INSERTS DE TB_EXPENSE_ITEM

BEGIN TRANSACTION;

INSERT INTO TB_EXPENSE_ITEM(IDEXPENSEITEM,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_ITEM' ), 'PROD', 'PRODUTO');

INSERT INTO TB_EXPENSE_ITEM(IDEXPENSEITEM,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_ITEM' ), 'SERV', 'SERVIÇO');

COMMIT TRANSACTION;

-- INSERTS DE TB_EXPENSE_STATUS

BEGIN TRANSACTION;

INSERT INTO TB_EXPENSE_STATUS(IDEXPENSESTATUS,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_STATUS' ), 'PAG', 'PAGO');

INSERT INTO TB_EXPENSE_STATUS(IDEXPENSESTATUS,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_STATUS' ), 'PAR', 'PAGO PARCIALMENTE');

INSERT INTO TB_EXPENSE_STATUS(IDEXPENSESTATUS,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_STATUS' ), 'PAR', 'NÃO INICIADO');

COMMIT TRANSACTION;

-- INSERTS DE TB_EXPENSE_STATUS

BEGIN TRANSACTION;

INSERT INTO TB_EXPENSE_TYPE(IDEXPENSETYPE,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_TYPE' ), 'PAG', 'PAGO');

INSERT INTO TB_EXPENSE_TYPE(IDEXPENSETYPE,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_TYPE' ), 'PAR', 'PAGO PARCIALMENTE');

INSERT INTO TB_EXPENSE_TYPE(IDEXPENSETYPE,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_TYPE' ), 'PAR', 'NÃO INICIADO');

COMMIT  TRANSACTION;

-- INSERTS DE TB_EXPENSE_OPERATION

BEGIN TRANSACTION;

INSERT INTO TB_EXPENSE_OPERATION(IDOPERATION,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_OPERATION' ), 'ADD', 'CADASTRO DE DESPESA');

INSERT INTO TB_EXPENSE_OPERATION(IDOPERATION,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_OPERATION' ), 'ALT', 'ALTERAÇÃO DE DESPESA');

INSERT INTO TB_EXPENSE_OPERATION(IDOPERATION,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_EXPENSE_OPERATION' ), 'DEL', 'EXCLUSÃO DE DESPESA');

COMMIT  TRANSACTION;