-- INSERTS DE TB_PHONE_TYPE

BEGIN TRANSACTION;

INSERT INTO TB_PHONE_TYPE (IDPHONETYPE,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_PHONE_TYPE' ), 'TEL', 'TELEFONE');

INSERT INTO TB_PHONE_TYPE (IDPHONETYPE,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_PHONE_TYPE' ), 'CEL', 'CELULAR');


COMMIT TRANSACTION;
