-- INSERTS DE TB_USER_TYPE

BEGIN TRANSACTION;

INSERT INTO TB_USER_TYPE (IDUSERTYPE,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_USER_TYPE' ), 'PRO', 'PROPRIETÁRIO');

INSERT INTO TB_USER_TYPE (IDUSERTYPE,CODE,DESCRIPTION)
VALUES ( nextval ( 'SQ_USER_TYPE' ), 'OPE', 'OPERADOR');


COMMIT TRANSACTION;
