-- INSERTS INICIAIS 001

-- INSERTS DE TB_PRODUCT_OPERATION
BEGIN TRANSACTION; 

INSERT INTO TB_PRODUCT_OPERATION ( IDOPERATION, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCT_OPERATION' ), 'ADD', 'CADASTRO DE PRODUTO');

INSERT INTO TB_PRODUCT_OPERATION ( IDOPERATION, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCT_OPERATION' ), 'STK', 'ALTERAÇÃO DE ESTOQUE');

INSERT INTO TB_PRODUCT_OPERATION ( IDOPERATION, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCT_OPERATION' ), 'PRD', 'ALTERAÇÃO DE TIPO DE PRODUÇÃO');

INSERT INTO TB_PRODUCT_OPERATION ( IDOPERATION, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCT_OPERATION' ), 'TVD', 'ALTERAÇÃO DE TIPO DE VENDA');

INSERT INTO TB_PRODUCT_OPERATION ( IDOPERATION, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCT_OPERATION' ), 'STTP', 'ALTERAÇÃO DE TIPO DE ESTOQUE');

INSERT INTO TB_PRODUCT_OPERATION ( IDOPERATION, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCT_OPERATION' ), 'DEL', 'EXCLUSÃO DE PRODUTO');

COMMIT TRANSACTION;



-- INSERTS DE TB_PRODUCTION_TYPE
BEGIN TRANSACTION;

INSERT INTO TB_PRODUCTION_TYPE ( IDPRODUCTIONTYPE, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCTION_TYPE' ), 'MUD', 'MUDAS');

INSERT INTO TB_PRODUCTION_TYPE ( IDPRODUCTIONTYPE, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_PRODUCTION_TYPE' ), 'SEM', 'SEMENTES');

COMMIT TRANSACTION;


-- INSERTS DE TB_SALE_TYPE
BEGIN TRANSACTION;

INSERT INTO TB_SALE_TYPE ( IDSALETYPE, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_SALE_TYPE' ), 'CAI', 'CAIXA');

COMMIT TRANSACTION;

-- INSERTS DE TB_STOCK_TYPE
BEGIN TRANSACTION;

INSERT INTO TB_STOCK_TYPE ( IDSTOCKTYPE, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_STOCK_TYPE' ), 'BAN', 'BANDEJA');

INSERT INTO TB_STOCK_TYPE ( IDSTOCKTYPE, CODE, DESCRIPTION )
VALUES ( nextval ( 'SQ_STOCK_TYPE' ), 'LAT', 'LATA');

COMMIT TRANSACTION;



















