-- TABELAS
CREATE TABLE TIPO_VENDA
(
  ID_TIPO_VENDA serial NOT NULL,
  DESCRIPTION character varying(50) NOT NULL,  
  INSERTDATE date NOT NULL,  
  CONSTRAINT TIPO_VENDA_PK PRIMARY KEY (ID_TIPO_VENDA)  
);

CREATE TABLE TIPO_UNIDADE
(
  ID_TIPO_UNIDADE serial NOT NULL,
  DESCRIPTION character varying(50) NOT NULL,  
  INSERTDATE date NOT NULL,  
  CONSTRAINT TIPO_UNIDADE_PK PRIMARY KEY (ID_TIPO_UNIDADE)
);

CREATE TABLE TIPO_PRODUCAO
(
  ID_TIPO_PRODUCAO serial NOT NULL,
  DESCRIPTION character varying(50) NOT NULL,  
  INSERTDATE date NOT NULL,  
  ID_TIPO_UNIDADE integer not null,
  CONSTRAINT TIPO_PRODUCAO_PK PRIMARY KEY (ID_TIPO_PRODUCAO),
  CONSTRAINT TIPO_UNIDADE_FK FOREIGN KEY(ID_TIPO_UNIDADE)
   REFERENCES TIPO_UNIDADE (ID_TIPO_UNIDADE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE PRODUTO
(
  ID_PRODUTO serial NOT NULL,
  DESCRIPTION character varying(50) NOT NULL,  
  INSERTDATE date NOT NULL,  
  ID_TIPO_PRODUCAO integer not null,
  ID_TIPO_VENDA integer not null,
  IMAGE_PATH character varying(250) NOT NULL,  
  PRECO NUMERIC(5,2) NOT NULL,  
  CONSTRAINT ID_PRODUTO_PK PRIMARY KEY (ID_PRODUTO),
  CONSTRAINT TIPO_VENDA_FK FOREIGN KEY(ID_TIPO_VENDA)
   REFERENCES TIPO_VENDA (ID_TIPO_VENDA) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT ID_TIPO_PRODUCAO FOREIGN KEY(ID_TIPO_PRODUCAO)
   REFERENCES TIPO_PRODUCAO (ID_TIPO_PRODUCAO) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION	
);

-- SEQUENCES
CREATE SEQUENCE SQ_TIPO_PRODUCAO START 3;
CREATE SEQUENCE SQ_TIPO_VENDA START 2;
CREATE SEQUENCE SQ_TIPO_UNIDADE START 3;
CREATE SEQUENCE SQ_PRODUTO START 1;
